import type { Metadata } from "next"
import "./styles/globals.scss"
import { ThemeProvider } from "@/components/ThemeProvide"
import Aside from "@/components/Aside"

export const metadata: Metadata = {
  // title: "Sergei Mazhuga",
  // description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="container text-[0.9375rem] text-[#171717] dark:text-[#ededed] dark:bg-[#161616] py-12">
        <ThemeProvider attribute="class" defaultTheme="dark" disableTransitionOnChange>
          <Aside />
          <main className="w-full max-w-[42rem] mx-auto">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  )
}
